--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Lycol50/ReportSystem
build-by-default: true
branches:
- master
- API4
projects:
  ReportSystem:
    path: ""
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.2
        branch: PM4
...
