name: Report
main: ImNotYourDev\Report\Report
api: 4.0.0
version: 2.0.0
author: ImNotYourDev, Lycol50

permissions:
  report:
    default: true
    description: Permission to access /report
  report.admin:
    description: open admin UI and Report list
    default: op
  report.list:
    description: show you an list of all reports
    default: op
