name: Report
main: ImNotYourDev\Report\Report
api: 4.0.0
version: 2
author: ImNotYourDev, Lycol50

permissions:
  reportsystem.admin:
    description: open admin ui and report list
    default: op
